export const LOAD_PRODUCTS_LIST = "LOAD_PRODUCTS_LIST";
export const SET_PRODUCT_FAVORITE = "SET_PRODUCT_FAVORITE";
export const FILTER_FAVORITE_PRODUCTS = "FILTER_FAVORITE_PRODUCTS";
export const LOAD_PRODUCT_SUCCEED = "LOAD_PRODUCT_SUCCEED";
